name: zenova-backend-dev
version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgrees-dev
    environment:
      - POSTGRES_USER=zenova-admin
      - POSTGRES_PASSWORD=zenova
      - POSTGRES_DB=zenova-app-mobile
    env_file:
      - .env
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

volumes:
  postgres-data-dev:
